# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import short_url.validators


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortingurl',
            name='costumer_code',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[short_url.validators.validate_min_length]),
        ),
    ]
