# Generated by Django 2.0.2 on 2018-05-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backgammon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='playerseason',
            options={'ordering': ['-win_ratio']},
        ),
    ]
