# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Optional description.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_eng', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('active_eng', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(help_text='The text appears on homepage', max_length=255)),
                ('description', models.TextField()),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title_eng', models.CharField(default='Insert Text', max_length=255)),
                ('short_description_eng', models.CharField(default='Insert Text', help_text='The text appears on homepage', max_length=255)),
                ('description_eng', models.TextField(default='Insert Text')),
                ('seo_description_eng', models.CharField(blank=True, default='Insert Text', max_length=255, null=True)),
                ('seo_keywords_eng', models.CharField(blank=True, default='Insert Text', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('day_added', models.DateField(auto_now_add=True)),
                ('href', models.CharField(max_length=255)),
                ('demo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectCategory')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='imageproject',
            name='project_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
