# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import projects.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='image',
            field=models.ImageField(upload_to='', validators=[projects.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description_eng',
            field=tinymce.models.HTMLField(default='Insert Text'),
        ),
    ]
