# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171004_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
