# Generated by Django 2.0.2 on 2018-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171004_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='show_first_page',
            field=models.BooleanField(default=True),
        ),
    ]
