# Generated by Django 2.0.7 on 2019-06-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_show_first_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='show_first_page',
            field=models.BooleanField(default=False),
        ),
    ]
