# Generated by Django 2.0.7 on 2019-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_templates', '0002_auto_20190602_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesample',
            name='free_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatesample',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
