# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 04:59
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gallery', max_length=30)),
                ('file', models.ImageField(upload_to=blog.models.gallery_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('active_eng', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('content', models.TextField(help_text='Use Html!!!', verbose_name='Content')),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('title_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title ENG')),
                ('content_eng', models.TextField(blank=True, help_text='Use Html!!!', null=True, verbose_name='Content_eng')),
                ('keywords_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Slug - Dont bother with that ')),
                ('file', models.ImageField(help_text='1332*550', upload_to='', verbose_name='Image')),
                ('update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
