# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 07:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170823_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=tinymce.models.HTMLField(blank=True, help_text='Use Html!!!', null=True, verbose_name='Content in eng'),
        ),
    ]
