# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170928_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together=set([('parent', 'slug')]),
        ),
    ]
