# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '7. Διαχείριση About Πελάτες',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50)),
                ('text', models.TextField(blank=True)),
                ('title_eng', models.CharField(default='default', max_length=50)),
                ('text_eng', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': '2. About Me Info',
            },
        ),
        migrations.CreateModel(
            name='AboutMeBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'About Programming Skill Bar - No use atm',
            },
        ),
        migrations.CreateModel(
            name='AboutMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('title_eng', models.CharField(max_length=50)),
                ('text_eng', models.TextField()),
                ('delay', models.CharField(default='.3s', max_length=5)),
            ],
            options={
                'verbose_name_plural': '5. Διαχείριση About Μυνημάτων',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.CharField(blank=True, max_length=160, null=True)),
                ('title_eng', models.CharField(max_length=50)),
                ('keywords_eng', models.CharField(blank=True, max_length=160, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Διαχείριση About Σελίδας',
            },
        ),
        migrations.CreateModel(
            name='AboutTecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=homepage.models.tech_upload)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('title_eng', models.CharField(max_length=50)),
                ('text_eng', models.TextField()),
                ('delay', models.CharField(default='.3s', max_length=5)),
                ('page_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage')),
            ],
            options={
                'verbose_name_plural': '6. Διαχείριση About Τεχνολογίες',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('day_added', models.DateField(auto_now_add=True)),
                ('is_readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('title_eng', models.CharField(max_length=100)),
                ('alt_eng', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=homepage.models.banner_upload)),
            ],
            options={
                'verbose_name_plural': 'Main Banner - Using static files atm for that',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html', max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=400)),
                ('title_eng', models.CharField(max_length=100)),
                ('text_eng', models.TextField(max_length=400)),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '3. Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('seo_keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('title_eng', models.CharField(max_length=100, unique=True)),
                ('seo_keywords_eng', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_description_eng', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Διαχείριση Αρχικής Σελίδας',
            },
        ),
        migrations.AddField(
            model_name='services',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.WelcomePage'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.WelcomePage'),
        ),
        migrations.AddField(
            model_name='aboutmessages',
            name='page_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage'),
        ),
        migrations.AddField(
            model_name='aboutmebar',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.WelcomePage'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.WelcomePage'),
        ),
        migrations.AddField(
            model_name='aboutclients',
            name='page_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage'),
        ),
    ]
