# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slugfield', models.SlugField(blank=True, null=True, unique=True)),
                ('deadlift', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('squats', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bench_press', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shoulder_press', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
